engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 25
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/**/*
